name: speech_practice_app
publish_to: "none"
description: Bilingual (Hindi + English) Speech Practice App with Flutter + Supabase
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.6.0
  intl: ^0.19.0
  provider: ^6.1.2
  http: ^1.2.2
  # Speech, audio, and TTS/STT helpers
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.2
  just_audio: ^0.9.39
  audio_session: ^0.1.21
  path_provider: ^2.1.3
  record: ^5.0.5
  percent_indicator: ^4.2.3
  fl_chart: ^0.68.0
  lottie: ^3.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0

  # For similarity scoring
  string_similarity: ^2.0.0

  # JSON and misc
  json_annotation: ^4.9.0

  # Firebase optional (disabled by default) - not used to keep costs free


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/
